# Generated by Django 5.0.6 on 2024-06-17 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekermodel',
            name='LastDegree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='JobInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=100, null=True)),
                ('CompanyName', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('CompanyDescription', models.TextField(null=True)),
                ('JobDescription', models.TextField(null=True)),
                ('Qualification', models.CharField(max_length=100, null=True)),
                ('Salary', models.CharField(max_length=100, null=True)),
                ('Deadline', models.CharField(max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('Experience', models.CharField(max_length=100, null=True)),
                ('PostedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'JobInfo_Table',
            },
        ),
        migrations.CreateModel(
            name='JobApplicantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.TextField(null=True)),
                ('Status', models.CharField(default='Pending', max_length=100, null=True)),
                ('Applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicantuser', to=settings.AUTH_USER_MODEL)),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobPortalApp.jobinfomodel')),
            ],
            options={
                'db_table': 'Applicant_Table',
            },
        ),
        migrations.CreateModel(
            name='QualificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DegreeName', models.CharField(max_length=100, null=True)),
                ('InstituteName', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('PassingYear', models.CharField(max_length=100, null=True)),
                ('Grade', models.CharField(max_length=100, null=True)),
                ('IonicUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Qualification_Table',
            },
        ),
        migrations.CreateModel(
            name='WorkExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('InstituteName', models.CharField(max_length=100, null=True)),
                ('Duration', models.CharField(max_length=100, null=True)),
                ('IonicUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workexperience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkExperience_Table',
            },
        ),
    ]
