# Generated by Django 5.0.6 on 2024-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0002_seekermodel_lastdegree_jobinfomodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekermodel',
            name='GitHub',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekermodel',
            name='LinkedIn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
