# Generated by Django 5.0.6 on 2024-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0004_alter_jobinfomodel_options_jobinfomodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinfomodel',
            old_name='Address',
            new_name='TotalVacancy',
        ),
        migrations.RemoveField(
            model_name='jobinfomodel',
            name='CompanyDescription',
        ),
        migrations.RemoveField(
            model_name='jobinfomodel',
            name='CompanyName',
        ),
        migrations.AddField(
            model_name='employermodel',
            name='CompanyDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobinfomodel',
            name='ExperienceLevel',
            field=models.CharField(choices=[('Begineer', 'Begineer'), ('Mid Level', 'Mid Level'), ('Experienced', 'Experienced'), ('TopLevel', 'TopLevel')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobinfomodel',
            name='JobType',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contractual', 'Contractual'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], max_length=100, null=True),
        ),
    ]
